//! builder_tools.zig — File-system and process tools for the Arcis Builder agent
//! These tools let the ReAct agent scaffold and refine full web apps from natural language.
//!
//! Safety rules:
//! - All paths are resolved under a fixed projects root (default: ./arcis-projects)
//! - Path traversal ("..") and absolute paths are rejected
//! - run_command is restricted to a small whitelist of safe commands inside the project dir

const std = @import("std");
const Allocator = std.mem.Allocator;
const Tool = @import("tool.zig").Tool;
const ToolRegistry = @import("tool.zig").ToolRegistry;

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

/// Root directory where all generated projects live.
pub var projects_root: []const u8 = "arcis-projects";

/// Simple in-memory map of running preview processes (project_name → pid).
/// Not persisted across restarts.
var preview_pids: ?std.StringHashMap(std.process.Child) = null;

fn ensurePreviewMap(allocator: Allocator) !*std.StringHashMap(std.process.Child) {
    if (preview_pids == null) {
        preview_pids = std.StringHashMap(std.process.Child).init(allocator);
    }
    return &preview_pids.?;
}

// ---------------------------------------------------------------------------
// Path helpers (security critical)
// ---------------------------------------------------------------------------

/// Reject path traversal and absolute paths. Returns cleaned relative path or error.
fn sanitizeRelPath(path: []const u8) ![]const u8 {
    if (path.len == 0) return error.EmptyPath;
    if (std.mem.startsWith(u8, path, "/") or std.mem.startsWith(u8, path, "\\")) {
        return error.AbsolutePathRejected;
    }
    if (std.mem.indexOf(u8, path, "..") != null) {
        return error.PathTraversalRejected;
    }
    // Strip leading "./"
    if (std.mem.startsWith(u8, path, "./")) return path[2..];
    return path;
}

/// Build full path: projects_root / project / rel_path
fn fullPath(allocator: Allocator, project: []const u8, rel: []const u8) ![]u8 {
    const clean_proj = try sanitizeRelPath(project);
    const clean_rel = if (rel.len == 0) "" else try sanitizeRelPath(rel);
    if (clean_rel.len == 0) {
        return std.fmt.allocPrint(allocator, "{s}/{s}", .{ projects_root, clean_proj });
    }
    return std.fmt.allocPrint(allocator, "{s}/{s}/{s}", .{ projects_root, clean_proj, clean_rel });
}

// ---------------------------------------------------------------------------
// Minimal JSON string extractor (same style as handlers.zig)
// ---------------------------------------------------------------------------

fn jsonGetString(body: []const u8, key: []const u8) ?[]const u8 {
    var needle_buf: [64]u8 = undefined;
    const needle = std.fmt.bufPrint(&needle_buf, "\"{s}\":\"", .{key}) catch return null;
    const start = std.mem.indexOf(u8, body, needle) orelse return null;
    const val_start = start + needle.len;
    // Handle escaped quotes naively: stop at first unescaped "
    var i = val_start;
    while (i < body.len) : (i += 1) {
        if (body[i] == '"' and (i == val_start or body[i - 1] != '\\')) {
            return body[val_start..i];
        }
    }
    return null;
}

// ---------------------------------------------------------------------------
// Tool handlers
// ---------------------------------------------------------------------------

/// create_project
/// Input: {"name": "my-app", "template": "vite-react" | "html" | "next"}
/// Creates the project directory and a minimal scaffold.
pub fn toolCreateProject(allocator: Allocator, input: []const u8) ![]u8 {
    const name = jsonGetString(input, "name") orelse return error.MissingName;
    const template = jsonGetString(input, "template") orelse "vite-react";

    const proj_path = try fullPath(allocator, name, "");
    defer allocator.free(proj_path);

    // Create root + src
    try std.fs.cwd().makePath(proj_path);

    if (std.mem.eql(u8, template, "html")) {
        // Minimal static HTML
        const index = try std.fmt.allocPrint(allocator,
            \\<!DOCTYPE html>
            \\ <html lang="en">
            \\ <head>
            \\   <meta charset="UTF-8" />
            \\   <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            \\   <title>{s}</title>
            \\   <style>
            \\     body {{ font-family: system-ui, sans-serif; max-width: 640px; margin: 2rem auto; padding: 0 1rem; }}
            \\   </style>
            \\ </head>
            \\ <body>
            \\   <h1>{s}</h1>
            \\   <p>Generated by Arcis Builder</p>
            \\ </body>
            \\ </html>
        , .{ name, name });
        defer allocator.free(index);

        const index_path = try fullPath(allocator, name, "index.html");
        defer allocator.free(index_path);
        try std.fs.cwd().writeFile(.{ .sub_path = index_path, .data = index });
    } else {
        // Default: simple Vite + React style scaffold (files only, user runs npm later)
        try std.fs.cwd().makePath(try fullPath(allocator, name, "src"));

        const pkg = try std.fmt.allocPrint(allocator,
            \\ {{
            \\   "name": "{s}",
            \\   "private": true,
            \\   "version": "0.0.1",
            \\   "type": "module",
            \\   "scripts": {{
            \\     "dev": "vite",
            \\     "build": "vite build",
            \\     "preview": "vite preview"
            \\   }},
            \\   "dependencies": {{
            \\     "react": "^18.3.1",
            \\     "react-dom": "^18.3.1"
            \\   }},
            \\   "devDependencies": {{
            \\     "@vitejs/plugin-react": "^4.3.1",
            \\     "vite": "^5.4.0"
            \\   }}
            \\ }}
        , .{name});
        defer allocator.free(pkg);

        const pkg_path = try fullPath(allocator, name, "package.json");
        defer allocator.free(pkg_path);
        try std.fs.cwd().writeFile(.{ .sub_path = pkg_path, .data = pkg });

        const index_html = try std.fmt.allocPrint(allocator,
            \\<!DOCTYPE html>
            \\ <html lang="en">
            \\   <head>
            \\     <meta charset="UTF-8" />
            \\     <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            \\     <title>{s}</title>
            \\   </head>
            \\   <body>
            \\     <div id="root"></div>
            \\     <script type="module" src="/src/main.jsx"></script>
            \\   </body>
            \\ </html>
        , .{name});
        defer allocator.free(index_html);

        const ih_path = try fullPath(allocator, name, "index.html");
        defer allocator.free(ih_path);
        try std.fs.cwd().writeFile(.{ .sub_path = ih_path, .data = index_html });

        const main_jsx =
            \\ import React from 'react'
            \\ import ReactDOM from 'react-dom/client'
            \\ import App from './App.jsx'
            \\ 
            \\ ReactDOM.createRoot(document.getElementById('root')).render(
            \\   <React.StrictMode>
            \\     <App />
            \\   </React.StrictMode>
            \\ )
        ;
        const main_path = try fullPath(allocator, name, "src/main.jsx");
        defer allocator.free(main_path);
        try std.fs.cwd().writeFile(.{ .sub_path = main_path, .data = main_jsx });

        const app_jsx = try std.fmt.allocPrint(allocator,
            \\ export default function App() {{
            \\   return (
            \\     <div style={{{{ fontFamily: 'system-ui', maxWidth: 640, margin: '2rem auto', padding: '0 1rem' }}}}>
            \\       <h1>{s}</h1>
            \\       <p>Generated by Arcis Builder</p>
            \\     </div>
            \\   )
            \\ }}
        , .{name});
        defer allocator.free(app_jsx);

        const app_path = try fullPath(allocator, name, "src/App.jsx");
        defer allocator.free(app_path);
        try std.fs.cwd().writeFile(.{ .sub_path = app_path, .data = app_jsx });

        // Minimal vite.config.js
        const vite_cfg =
            \\ import { defineConfig } from 'vite'
            \\ import react from '@vitejs/plugin-react'
            \\ 
            \\ export default defineConfig({
            \\   plugins: [react()],
            \\ })
        ;
        const vite_path = try fullPath(allocator, name, "vite.config.js");
        defer allocator.free(vite_path);
        try std.fs.cwd().writeFile(.{ .sub_path = vite_path, .data = vite_cfg });
    }

    return try std.fmt.allocPrint(allocator,
        "{{\"ok\":true,\"project\":\"{s}\",\"path\":\"{s}\",\"template\":\"{s}\"}}",
        .{ name, proj_path, template },
    );
}

/// write_file
/// Input: {"project": "my-app", "path": "src/App.jsx", "content": "..."}
pub fn toolWriteFile(allocator: Allocator, input: []const u8) ![]u8 {
    const project = jsonGetString(input, "project") orelse return error.MissingProject;
    const path = jsonGetString(input, "path") orelse return error.MissingPath;
    const content = jsonGetString(input, "content") orelse return error.MissingContent;

    // Note: content may contain escaped characters. For a real implementation
    // we would properly unescape JSON. For now we accept the raw slice.
    const full = try fullPath(allocator, project, path);
    defer allocator.free(full);

    // Ensure parent directories exist
    if (std.fs.path.dirname(full)) |dir| {
        try std.fs.cwd().makePath(dir);
    }

    try std.fs.cwd().writeFile(.{ .sub_path = full, .data = content });

    return try std.fmt.allocPrint(allocator,
        "{{\"ok\":true,\"wrote\":\"{s}\",\"bytes\":{d}}}",
        .{ full, content.len },
    );
}

/// read_file
/// Input: {"project": "my-app", "path": "src/App.jsx"}
pub fn toolReadFile(allocator: Allocator, input: []const u8) ![]u8 {
    const project = jsonGetString(input, "project") orelse return error.MissingProject;
    const path = jsonGetString(input, "path") orelse return error.MissingPath;

    const full = try fullPath(allocator, project, path);
    defer allocator.free(full);

    const data = try std.fs.cwd().readFileAlloc(allocator, full, 1024 * 1024); // 1 MB limit
    defer allocator.free(data);

    // Escape for JSON (minimal)
    var escaped = std.ArrayList(u8).init(allocator);
    defer escaped.deinit();
    for (data) |c| {
        switch (c) {
            '"' => try escaped.appendSlice("\\\""),
            '\\' => try escaped.appendSlice("\\\\"),
            '\n' => try escaped.appendSlice("\\n"),
            '\r' => try escaped.appendSlice("\\r"),
            '\t' => try escaped.appendSlice("\\t"),
            else => try escaped.append(c),
        }
    }

    return try std.fmt.allocPrint(allocator,
        "{{\"ok\":true,\"path\":\"{s}\",\"content\":\"{s}\"}}",
        .{ full, escaped.items },
    );
}

/// list_files
/// Input: {"project": "my-app", "path": ""}  (path optional, defaults to root)
pub fn toolListFiles(allocator: Allocator, input: []const u8) ![]u8 {
    const project = jsonGetString(input, "project") orelse return error.MissingProject;
    const path = jsonGetString(input, "path") orelse "";

    const full = try fullPath(allocator, project, path);
    defer allocator.free(full);

    var dir = try std.fs.cwd().openDir(full, .{ .iterate = true });
    defer dir.close();

    var list = std.ArrayList(u8).init(allocator);
    defer list.deinit();
    try list.appendSlice("{\"ok\":true,\"files\":[");

    var first = true;
    var it = dir.iterate();
    while (try it.next()) |entry| {
        if (!first) try list.appendSlice(",");
        first = false;
        const kind = if (entry.kind == .directory) "dir" else "file";
        try list.writer().print("{{\"name\":\"{s}\",\"type\":\"{s}\"}}", .{ entry.name, kind });
    }
    try list.appendSlice("]}");

    return try list.toOwnedSlice();
}

/// run_command (restricted)
/// Input: {"project": "my-app", "command": "npm install"}
/// Only allows a small whitelist of safe commands.
pub fn toolRunCommand(allocator: Allocator, input: []const u8) ![]u8 {
    const project = jsonGetString(input, "project") orelse return error.MissingProject;
    const command = jsonGetString(input, "command") orelse return error.MissingCommand;

    // Whitelist
    const allowed = [_][]const u8{
        "npm install",
        "npm run dev",
        "npm run build",
        "npm run preview",
        "pnpm install",
        "pnpm dev",
        "yarn",
        "yarn install",
        "yarn dev",
    };

    var ok = false;
    for (allowed) |a| {
        if (std.mem.eql(u8, command, a) or std.mem.startsWith(u8, command, a)) {
            ok = true;
            break;
        }
    }
    if (!ok) {
        return try std.fmt.allocPrint(allocator,
            "{{\"ok\":false,\"error\":\"command not in whitelist: {s}\"}}",
            .{command},
        );
    }

    const proj_path = try fullPath(allocator, project, "");
    defer allocator.free(proj_path);

    // Split command into argv (very simple)
    var argv = std.ArrayList([]const u8).init(allocator);
    defer argv.deinit();
    var parts = std.mem.splitScalar(u8, command, ' ');
    while (parts.next()) |p| {
        if (p.len > 0) try argv.append(p);
    }

    var child = std.process.Child.init(argv.items, allocator);
    child.cwd = proj_path;
    child.stdout_behavior = .Pipe;
    child.stderr_behavior = .Pipe;

    try child.spawn();
    const stdout = try child.stdout.?.reader().readAllAlloc(allocator, 64 * 1024);
    defer allocator.free(stdout);
    const stderr = try child.stderr.?.reader().readAllAlloc(allocator, 64 * 1024);
    defer allocator.free(stderr);
    const term = try child.wait();

    const exit_code: i32 = switch (term) {
        .Exited => |c| @intCast(c),
        else => -1,
    };

    // Escape output for JSON (minimal)
    var esc_out = std.ArrayList(u8).init(allocator);
    defer esc_out.deinit();
    for (stdout) |c| {
        if (c == '"' or c == '\\' or c == '\n') try esc_out.append('\\');
        try esc_out.append(c);
    }

    return try std.fmt.allocPrint(allocator,
        "{{\"ok\":true,\"exit_code\":{d},\"stdout\":\"{s}\",\"stderr_len\":{d}}}",
        .{ exit_code, esc_out.items, stderr.len },
    );
}

/// start_preview
/// Input: {"project": "my-app", "port": "5173"}
/// Starts `npm run dev` in background and records the process.
pub fn toolStartPreview(allocator: Allocator, input: []const u8) ![]u8 {
    const project = jsonGetString(input, "project") orelse return error.MissingProject;
    const port = jsonGetString(input, "port") orelse "5173";

    const proj_path = try fullPath(allocator, project, "");
    defer allocator.free(proj_path);

    var child = std.process.Child.init(&.{ "npm", "run", "dev", "--", "--port", port, "--host" }, allocator);
    child.cwd = proj_path;
    child.stdout_behavior = .Ignore;
    child.stderr_behavior = .Ignore;

    try child.spawn();

    const map = try ensurePreviewMap(allocator);
    // Store a copy of the name so the map owns the key
    const key = try allocator.dupe(u8, project);
    try map.put(key, child);

    return try std.fmt.allocPrint(allocator,
        "{{\"ok\":true,\"project\":\"{s}\",\"url\":\"http://localhost:{s}\",\"pid\":{d}}}",
        .{ project, port, child.id },
    );
}

/// stop_preview
/// Input: {"project": "my-app"}
pub fn toolStopPreview(allocator: Allocator, input: []const u8) ![]u8 {
    const project = jsonGetString(input, "project") orelse return error.MissingProject;

    const map = try ensurePreviewMap(allocator);
    if (map.fetchRemove(project)) |kv| {
        _ = kv.value.kill() catch {};
        allocator.free(kv.key);
        return try std.fmt.allocPrint(allocator,
            "{{\"ok\":true,\"stopped\":\"{s}\"}}",
            .{project},
        );
    }
    return try std.fmt.allocPrint(allocator,
        "{{\"ok\":false,\"error\":\"no running preview for {s}\"}}",
        .{project},
    );
}

// ---------------------------------------------------------------------------
// Registration helper
// ---------------------------------------------------------------------------

/// Register all builder tools into a ToolRegistry.
pub fn registerBuilderTools(registry: *ToolRegistry) !void {
    try registry.register(.{ .name = "create_project", .description = "Create a new project scaffold. Args: name, template (vite-react|html)", .handler = toolCreateProject });
    try registry.register(.{ .name = "write_file", .description = "Write content to a file inside a project. Args: project, path, content", .handler = toolWriteFile });
    try registry.register(.{ .name = "read_file", .description = "Read a file from a project. Args: project, path", .handler = toolReadFile });
    try registry.register(.{ .name = "list_files", .description = "List files/directories in a project path. Args: project, path (optional)", .handler = toolListFiles });
    try registry.register(.{ .name = "run_command", .description = "Run a whitelisted command (npm install, npm run dev, etc) inside the project. Args: project, command", .handler = toolRunCommand });
    try registry.register(.{ .name = "start_preview", .description = "Start the dev server for a project and return the local URL. Args: project, port (optional)", .handler = toolStartPreview });
    try registry.register(.{ .name = "stop_preview", .description = "Stop a running preview. Args: project", .handler = toolStopPreview });
}
